### ISSUE TITLE
How to set time range?

### ISSUE THREAD

**Issue by rosevinod** [TomThorpe/TTRangeSlider#17]
Thanks for the awesome TTRangeSlider. But can you tell  me how to set time range?
like 10:00 AM to 10:00 PM

**Comment by fiantinangon** [comment]
Try to format your time from 1-24 and change the label to AM PM format like 10 AM mean 10 and 10PM mean 22

**Comment by rosevinod** [comment]
what is the delegate to update the label @run time..... why can't you just simply add time feature by default. its very useful.

**Comment by TomThorpe** [comment]
I would go with what @fiantinangon said above and set your range to be 1-24 then use the numberFormatterOverride property (it's not a delegate) to set a number formatter that converts numbers to time format (keeping in mind device locale)

I do understand it would be a useful feature but i don't want to add it to the control because it's too specific - the numberFormatterOverride is there for these cases to allow you to customise it without complicating the control's set of features

**Comment by TomThorpe** [comment]
Thanks for the kind comments about the control though! :-)
