### ISSUE TITLE
Data reset after scroll

### ISSUE THREAD

**Issue by MohammadEhsanMirzaaee** [TomThorpe/TTRangeSlider#90]
Hi, thank you for your slider, I added your slider to a dynamic table view cell it's work fine until I scroll down and return up, it's reset all data that user select on slider to default value

**Comment by TomThorpe** [comment]
Hi,

This will be because table view cells are reused and don't persist past the edge of the screen (when they scroll off screen they will be removed from the tableview, and when they return back to screen the cell is re-added based on the call from the datasource to get a tableview cell for index x). When you return the cell in your table view datasource you will need to set the values on the slider again.
